SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
include $(SELF_DIR)deps-core-*
CORE_ALL_DEPS := $(DEPS_SOLVE_TMP)
CORE_ALL_RTL_SRCS := $(RTL_SRCS_SOLVE_TMP)
CORE_ALL_SIM_SRCS := $(SIM_SRCS_SOLVE_TMP)
CORE_ALL_PREREQ := $(PREREQ_SOLVE_TMP)
